# Configuration Render - Infrastructure as Code
# Permet de déployer automatiquement backend + frontend + database

services:
  # Backend FastAPI
  - type: web
    name: devops-app-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devops-db
          property: connectionString
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
    region: frankfurt

  # Frontend Node.js/Express
  - type: web
    name: devops-app-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: devops-app-backend
          property: host
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    region: frankfurt

# Base de données PostgreSQL
databases:
  - name: devops-db
    databaseName: devops_db
    user: devops_user
    region: frankfurt
    plan: free
    ipAllowList: []
