# Configuration Render - Infrastructure as Code
# Image unique contenant Backend + Frontend + PostgreSQL
# Solution pour plan gratuit Render (1 seul service web)

services:
  # Application complète (backend + frontend + database)
  - type: web
    name: devops-app
    runtime: image
    image:
      url: docker.io/azylos/tp-devops:latest
    envVars:
      - key: PORT
        value: 8080
      - key: BACKEND_PORT
        value: 8000
      - key: POSTGRES_USER
        value: devops_user
      - key: POSTGRES_PASSWORD
        value: devops_password
      - key: POSTGRES_DB
        value: devops_db
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /
    autoDeploy: true
    region: frankfurt
    plan: free
    # Render expose automatiquement le port 8080 (frontend)
    # Le backend tourne en interne sur le port 8000
